CREATE TABLE `users`
(
  id int(11) NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  firstname VARCHAR(100),
  lastname VARCHAR(120),
  role_id VARCHAR(3) NOT NULL DEFAULT '2Ci',
  is_active TINYINT(1) DEFAULT 0,
  ok_newsletter TINYINT(1) DEFAULT 0,
  created DATETIME,
  modified DATETIME
)ENGINE=InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE `roles`
(
  id VARCHAR(3) UNIQUE PRIMARY KEY,
  name VARCHAR(200)
)ENGINE=InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE `categories`
(
  id INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL UNIQUE
)ENGINE=InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE `products`
(
  id INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  description TEXT,
  price VARCHAR(8) NOT NULL,
  categorie_id INT NOT NULL
)ENGINE=InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE `orders`
(
  id INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL
)ENGINE=InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE `orders_products`
(
  id int NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
  order_id INT NOT NULL,
  product_id INT NOT NULL,
  quantity INT NOT NULL DEFAULT 1
)ENGINE=InnoDB  DEFAULT CHARSET=utf8;



INSERT INTO roles (id,name) VALUES ('7cH','Administrateur'),
('2Ci','Membre');